### Hulp Notebook om objecten op map.png te zetten, kleurwaarden te analyseren en afbeelding te evalueren

In [2]:
import cv2 
import numpy as np

### objecten op map plaatsen met behulp van muis

In [ ]:


# Load the image
img = cv2.imread('map.png')

# Display the image
cv2.imshow('image', img)

# Define a callback function to handle mouse events
def draw_rect(event, x, y, flags, param):
    global ix, iy, drawing, img
    print(f"x: {x} en y:{y}")
    if event == cv2.EVENT_LBUTTONDOWN:
        drawing = True
        ix, iy = x, y
    elif event == cv2.EVENT_LBUTTONUP:
        drawing = False
        cv2.rectangle(img, (ix, iy), (x, y), (255, 255, 255), 2)
        for i in range(iy, y):
            for j in range(ix, x):
                img[i, j] = [255, 255, 255]
        cv2.imshow('image', img)
        # cv2.imwrite("map_v2.png", img)

# Set the mouse callback function
cv2.setMouseCallback('image', draw_rect)

# Wait for a key press to exit
cv2.waitKey(0)

# Clean up
cv2.destroyAllWindows()


### BGR grijswaarde van track vinden

In [4]:
# Load the image
img = cv2.imread('map.png')

img_black = img[img < (100, 100,100)]

# punten op track
print(img[681, 876])
print(img[682, 877])

[ 97 106 100]
[ 97 106 100]


### alle unieke pixelwaarden in map vinden
At first, we flatten rows and columns of matrix. Now the matrix has as much rows as there're pixels in the image. Columns are color components of each pixels.

In [16]:
# print(img)
map2 = cv2.imread("map_v2.png")

unieke_kleuren = np.unique(map2.reshape(-1, img.shape[2]), axis=0)
unieke_kleuren

for i in range(unieke_kleuren.shape[0]):
    # for j in range(unieke_kleuren.shape[1]):
        print(unieke_kleuren[i])



[0 0 0]
[69 80 72]
[70 82 76]
[73 84 77]
[73 84 78]
[73 85 77]
[74 83 76]
[74 83 77]
[74 84 77]
[74 85 76]
[74 85 78]
[74 85 79]
[74 85 80]
[74 86 78]
[74 86 79]
[75 84 78]
[75 85 77]
[75 85 78]
[75 85 79]
[75 85 80]
[75 86 77]
[75 86 78]
[75 86 79]
[75 86 80]
[75 86 81]
[75 87 79]
[75 87 81]
[76 85 78]
[76 85 79]
[76 86 79]
[76 86 80]
[76 86 81]
[76 87 79]
[76 87 80]
[76 87 81]
[76 87 82]
[76 88 80]
[76 88 81]
[76 88 83]
[76 89 80]
[77 86 78]
[77 86 80]
[77 86 81]
[77 87 79]
[77 87 80]
[77 87 81]
[77 87 82]
[77 87 84]
[77 88 80]
[77 88 81]
[77 88 82]
[77 88 83]
[77 89 81]
[77 89 82]
[77 89 84]
[77 89 85]
[78 87 80]
[78 87 81]
[78 87 82]
[78 88 80]
[78 88 81]
[78 88 82]
[78 88 83]
[78 89 81]
[78 89 82]
[78 89 83]
[78 89 84]
[78 90 81]
[78 90 82]
[78 90 83]
[78 90 86]
[78 91 86]
[79 88 80]
[79 88 81]
[79 88 82]
[79 88 83]
[79 89 81]
[79 89 82]
[79 89 83]
[79 89 84]
[79 89 86]
[79 90 81]
[79 90 82]
[79 90 83]
[79 90 84]
[79 90 85]
[79 90 87]
[79 91 83]
[79 91 84]
[79 91 87]
[80 88 81]
[8