### Hulp Notebook om objecten op map.png te zetten, kleurwaarden te analyseren en afbeelding te evalueren

In [1]:
import cv2 
import numpy as np

In [2]:
def to_screen(name, file):
    cv2.imshow(name, file)  
    cv2.waitKey(0)
    cv2.destroyAllWindows()  

### objecten op map plaatsen met behulp van muis

In [7]:


# Load the image
img = cv2.imread('straat_v3.png')

# Display the image
cv2.imshow('image', img)

# Define a callback function to handle mouse events
def draw_rect(event, x, y, flags, param):
    global ix, iy, drawing, img
    # print(f"x: {x} en y:{y}")
    if event == cv2.EVENT_LBUTTONDOWN:
        drawing = True
        ix, iy = x, y
    elif event == cv2.EVENT_LBUTTONUP:
        drawing = False
        cv2.rectangle(img, (ix, iy), (x, y), (255, 255, 255), 2)
        for i in range(iy, y):
            for j in range(ix, x):
                img[i, j] = [255, 255, 255]
        cv2.imshow('image', img)
        cv2.imwrite("straat_v4.png", img)

# Set the mouse callback function
cv2.setMouseCallback('image', draw_rect)

# Wait for a key press to exit
cv2.waitKey(0)

# Clean up
cv2.destroyAllWindows()


### BGR grijswaarde van track vinden

In [4]:
# Load the image
img = cv2.imread('map.png')

img_black = img[img < (100, 100,100)]

# punten op track
print(img[681, 876])
print(img[682, 877])

[ 97 106 100]
[ 97 106 100]


### alle unieke pixelwaarden in map vinden
At first, we flatten rows and columns of matrix. Now the matrix has as much rows as there're pixels in the image. Columns are color components of each pixels.

In [ ]:
# print(img)
map2 = cv2.imread("map_v2.png")

unieke_kleuren = np.unique(map2.reshape(-1, img.shape[2]), axis=0)
unieke_kleuren

for i in range(unieke_kleuren.shape[0]):
    # for j in range(unieke_kleuren.shape[1]):
        print(unieke_kleuren[i])



### pixels wit maken

In [15]:
straat_v3 = cv2.imread("straat_v3.png")


straat_v3[:, :27] = 255

# Display the image
cv2.imshow('image', straat_v3)

# Wait for a key press to exit
cv2.waitKey(0)

# Clean up
cv2.destroyAllWindows()

cv2.imwrite("straat_v4.png", straat_v3)

True

### padden met wit langs rechts


In [17]:
straat_breder_wit = cv2.imread("./afbeeldingen/straat_meer_bochten_links.png")
print(straat_breder_wit.shape)

# padden
npad = ((0, 0), (771, 771), (0,0))
straat_breder_wit = np.pad(straat_breder_wit, npad, mode='constant', constant_values=255)
print(straat_breder_wit.shape)

to_screen("straat_breder_wit", straat_breder_wit)

cv2.imwrite("./afbeeldingen/straat_meer_bochten_links.png", straat_breder_wit)


(1440, 510, 3)
(1440, 2052, 3)


True

### grijs aanvullen op sommige plekken zodat spel speelbaar is 

In [14]:
straat_meer_bochten_links = cv2.imread("./afbeeldingen/straat_meer_bochten_links.png")
straat_meer_bochten_links.shape
color_grey  = straat_meer_bochten_links[1170][195]
print(color_grey)

straat_meer_bochten_links[930:989, 239:256, :] = color_grey
cv2.imwrite("./afbeeldingen/straat_meer_bochten_links.png", straat_meer_bochten_links)

[ 97 106 100]


True

### rescalen van image

In [20]:
img = cv2.imread('./afbeeldingen/straat_meer_bochten_links.png', cv2.IMREAD_UNCHANGED)
 
print('Original Dimensions : ',img.shape)
 
scale_percent = 60 # percent of original size
width = int(img.shape[1] * scale_percent / 100)
height = int(img.shape[0] * scale_percent / 100)
dim = (width, height)
  
# resize image
resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
 
print('Resized Dimensions : ',resized.shape)
to_screen("Resized image", resized)
cv2.imwrite("./afbeeldingen/straat_meer_bochten_links.png", resized)

Original Dimensions :  (1440, 2052, 3)
Resized Dimensions :  (864, 1231, 3)


True

### Straat zwart maken en vierkantig

In [3]:
img = cv2.imread('./afbeeldingen/contrast_v3.jpg')

threshold = 130

img[img > 140] = 255
img[img <= 140] = 0

cv2.imwrite("./afbeeldingen/contrast_v3.jpg", img)

True